CREATE TABLE USER_ACCOUNT
(
  ID            BIGINT NOT NULL,
  LOGIN         CHARACTER VARYING(128),
  EMAIL         CHARACTER VARYING(128),
  FIRST_NAME    CHARACTER VARYING(128),
  LAST_NAME     CHARACTER VARYING(128),
  PASSWORD_HASH CHARACTER VARYING(128),
  SALT          CHARACTER VARYING(128),
  CONSTRAINT USER_ACCOUNT_PKEY PRIMARY KEY (ID)
);

CREATE SEQUENCE USER_ACCOUNT_IDS;

CREATE TABLE ARTIFACT (
  ID               BIGINT NOT NULL PRIMARY KEY,
  NAME             VARCHAR(256),
  DESCRIPTION      VARCHAR(1024),
  TIME_START       TIMESTAMP,
  TIME_END         TIMESTAMP,
  CUBE_COORDINATES VARCHAR(2048)
);

CREATE SEQUENCE ARTIFACT_IDS;

CREATE TABLE CUBE_DESCRIPTION (
ID                BIGINT NOT NULL PRIMARY KEY,
NAME              CHARACTER VARYING(128),
DIMENSIONS        CHARACTER VARYING(128),
AGGREGATES        CHARACTER VARYING(128),
TYPES             CHARACTER VARYING(1024),
);

CREATE SEQUENCE CUBE_DESCRIPTION_IDS;

CREATE TABLE REPORT_CONFIG (
  ID              BIGINT NOT NULL PRIMARY KEY,
  CUBE_ID         BIGINT NOT NULL FOREIGN KEY REFERENCES CUBE_DESCRIPTION (ID),
  NAME            CHARACTER VARYING(128),
  QUERY           CHARACTER VARYING(2048),
  PERIOD          BIGINT NOT NULL,
  PERIOD_UNITS    CHARACTER VARYING(128),
  LAST_BUILD_TIME TIMESTAMP,
  USE_CACHE       BOOLEAN,
  CACHE_ALL       BOOLEAN,
  CACHE_MASK      CHARACTER VARYING(128),
  CACHE_MAX_AGE   BIGINT,
  CACHE_MAX_AGE_UNITS CHARACTER VARYING(128),
  CACHE_MAX_SIZE  BIGINT,
  ANALYZE_ALL     BOOLEAN

);

CREATE SEQUENCE REPORT_CONFIG_IDS;
